---
#- name: Install DB package
#  yum: name={{ item }} state=present
#  with_items:
#  - mysql-client 
#  - mysql-devel 
#  - mysql-server

- name: Create DB configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart db

- name: Start DB Service
  service: name=mysql state=started enabled=yes
